import { Theme, Icons } from "../../theme.slint";
import { Util } from "../../util.slint";
import { Logic } from "../../logic.slint";
import { Store } from "../../store.slint";

import { SettingEntryV2, CenterLayout, ConfirmDialogSetting, Search, Label, IconBtn } from "../../base/widgets.slint";

export component BtnField inherits VerticalLayout {
    private property <length> btn-width: Math.min(root.width * 25%, 120px);

    alignment: LayoutAlignment.start;

    HorizontalLayout {
        spacing: Theme.spacing * 4;
        alignment: LayoutAlignment.center;
        height: Theme.icon-size + Theme.padding * 2;

        IconBtn {
            width: root.btn-width;
            icon: Icons.add-light;
            bg-color: Theme.success-color;
            text-color: Theme.light-text-color;
            colorize: self.text-color;
            text: Logic.tr("Add");

            clicked() => {
                Store.edit-entry = Store.clean-entry;
                Store.is-show-edit-dialog = true;
            }
        }

        IconBtn {
            width: root.btn-width;
            icon: Icons.edit;
            bg-color: Theme.info-color;
            text-color: Theme.light-text-color;
            colorize: self.text-color;
            text: Logic.tr("Edit");

            clicked() => {
                if (Store.edit-entry.uuid == "") {
                    return;
                }
                Store.is-show-edit-dialog = true;
            }
        }

        IconBtn {
            width: root.btn-width;
            icon: Icons.delete;
            bg-color: Theme.danger-color;
            text-color: Theme.light-text-color;
            colorize: self.text-color;
            text: Logic.tr("Delete");

            clicked() => {
                ConfirmDialogSetting.set(true, Logic.tr("Warning"), Logic.tr("Delete or not?"), "delete-entry", Store.edit-entry.uuid);
            }
        }
    }
}
