import "fonts/SourceHanSerifCN.ttf";
import "fonts/SourceHanSansCN.otf";

import { Util } from "util.slint";
import { Logic } from "logic.slint";
import { Theme, Icons } from "theme.slint";
import { Store, SettingDetailIndex, DeviceType, SettingProxy } from "store.slint";

import { DesktopPanel } from "panel/desktop/panel.slint";
import { SettingIconsBar } from "panel/setting/desktop.slint";
import { LoadingStatus, Toast, IconsDialogSetting, ConfirmDialog, ConfirmDialogSetting, Blanket, LandingPage, AboutSetting, ToastSetting, ToastStatus, AppPosType, PopupActionSetting } from "base/widgets.slint";

export component AppWindow inherits Window {
    width: Theme.default-width;
    height: Theme.default-height;
    default-font-size: Theme.default-font-size;
    default-font-weight: Theme.normal-font-weight;
    default-font-family: Theme.default-font-family;
    background: Theme.base-background;
    icon: Icons.brand;
    title: AboutSetting.app-name;
    no-frame: Store.setting-preference.no-frame;
    always-on-top: Store.setting-preference.always-on-top;

    DesktopPanel { }

    if IconsDialogSetting.show || ConfirmDialogSetting.show: Blanket {
        clicked => {
            IconsDialogSetting.show = false;
            ConfirmDialogSetting.show = false;
        }
    }

    if ConfirmDialogSetting.show: ConfirmDialog {
        is-prevent-event-forward: true;
        width: Math.min(root.width * 0.9, self.vbox-preferred-width * 2);
    }

    if !ToastSetting.is-timeout || ToastSetting.is-hover: Toast {
        x: root.width / 2 - self.width / 2;
        y: 50px;
        inner-max-width: root.width * 80%;
        clicked => {
            Logic.copy-to-clipboard(ToastSetting.text);
        }
    }
}

export {
    AppPosType, Util, Logic, Store, Theme, Icons, IconsDialogSetting, LoadingStatus, SettingDetailIndex, AboutSetting, ToastSetting, ToastStatus, DeviceType , SettingProxy, PopupActionSetting
    }
